#!/bin/bash

# The `environment` hook will run before all other commands, and can be used
# to set up secrets, data, etc. Anything exported in hooks will be available
# to the build script.
#
# For example:
#
# export SECRET_VAR=token

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

set -e

export BUILDKITE_CLEAN_CHECKOUT=true
export BUILDKITE_NO_LOCAL_HOOKS=true

export X_PARALLEL_JOBS=$(sysctl -n hw.ncpu)
