#!/usr/bin/env bash

set -e

if [ -z "$BUILDKITE_AGENT_TOKEN" ]
then
	echo "Not configuring buildkite-agent - BUILDKITE_AGENT_TOKEN is not set" 1>&2
	exit
fi

if [ -z "$BUILDKITE_AGENT_SPAWN" ]
then
	echo "Not configuring buildkite-agent - BUILDKITE_AGENT_SPAWN is not set" 1>&2
	exit
fi

sed \
	-e "s/BUILDKITE_AGENT_TOKEN/${BUILDKITE_AGENT_TOKEN}/g" \
	-e "s/BUILDKITE_AGENT_SPAWN/${BUILDKITE_AGENT_SPAWN}/g" \
	< /etc/buildkite-agent/buildkite-agent.cfg.in \
	> /etc/buildkite-agent/buildkite-agent.cfg

cat << EOF > /etc/buildkite-agent/buildkite-agent.env
if [ -n "$http_proxy" ]
then
	export http_proxy="$http_proxy"
	export HTTP_PROXY="$http_proxy"
fi

if [ -n "$https_proxy" ]
then
	export https_proxy="$https_proxy"
	export HTTPS_PROXY="$https_proxy"
fi
EOF

touch /tmp/buildkite-configured
