#!/usr/bin/env bash

set -e

if [ -z "$BUILDKITE_AGENT_TOKEN" ]
then
	echo "Not configuring buildkite-agent - BUILDKITE_AGENT_TOKEN is not set" 1>&2
	exit
fi

if [ -z "$BUILDKITE_AGENT_SPAWN" ]
then
	echo "Not configuring buildkite-agent - BUILDKITE_AGENT_SPAWN is not set" 1>&2
	exit
fi

sed \
	-e "s/BUILDKITE_AGENT_TOKEN/${BUILDKITE_AGENT_TOKEN}/g" \
	-e "s/BUILDKITE_AGENT_SPAWN/${BUILDKITE_AGENT_SPAWN}/g" \
	< /etc/buildkite-agent/buildkite-agent.cfg.in \
	> /etc/buildkite-agent/buildkite-agent.cfg

touch /tmp/buildkite-configured
