#!/bin/bash

# The `pre-exit` hook will run just before your build job finishes

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

if [ -e ~/.test-machine-powered-on ]
then
	echo "Powering off test machine..."
	http_proxy="" curl -X POST -s "http://rx100-power.build.solemnwarning.net/hard-off"
	
	rm -f "~/.test-machine-powered-on"
fi
