#!/bin/bash

# The `pre-exit` hook will run just before your build job finishes

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

if [ -n "$QEMU_PID" ]
then
	echo "Terminating QEMU ($QEMU_PID)"
	kill -KILL "$QEMU_PID"
fi

if [ -n "$QEMU_DISK" ]
then
	echo "Deleting QEMU disk image ($QEMU_DISK)"
	rm -f "$QEMU_DISK"
fi
